name: dsf continuous testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repository
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build the Docker Test Container
        run: docker build . --file Dockerfile --tag aht/dsf
      -
        name: Lint code with black codestyle checker
        run: docker run aht/dsf black --check --diff .
      -
        name: Test Code
        run: docker run aht/dsf python dsf_test.py
